### ISSUE TITLE
not "opens java.io"

### ISSUE THREAD

**Issue by Wentao-Luo-Bose** [s1204IT/Android-Stub-APK-Maker#1]
Building is reported this error.

module java.base does not "opens java.io" to unnamed module @3c4904c

Solution:
Modify project build.grad
Change gradle 4.1.3 to 7.3.1.
4.1.3 has not "opens java.io" error.

**Comment by s1204IT** [comment]
Thank you for your feedback.  
I'm working on a fix.

**Comment by s1204IT** [comment]
This should fix it.  
Please confirm.
